version: 1.0.{build}-{branch}

cache:
  - vendor/bundle

environment:
  matrix:
    # - RUV: 23
    - RUV: 22
    - RUV: 21
    - RUV: 200

install:
  - set PATH=C:\Ruby%RUV%\bin;%PATH%
  - ruby -v
  - gem -v
  - bundle -v
  - bundle config --local path vendor/bundle
  - bundle

build: off

test_script:
  - bundle exec rake
