version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - node -v
  - npm -v
  - npm install

build: off

before_test:
  - cscript

test_script:
  - npm test

artifacts:
  - path: config.zip
    name: Test ZIP
    type: zip
