version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUV: 22
    - RUV: 21
    - RUV: 200
    - RUV: 193

install:
  - set PATH=C:\Ruby%RUV%\bin;%PATH%
  - ruby -v
  - gem -v
  - bundle -v

build: off

test_script:
  - bundle
