environment:
  matrix:
    - RUV: 22
    - RUV: 21
    - RUV: 200
    - RUV: 193

install:
  - set PATH=C:\Ruby%RUV%\bin;%PATH%

build: off

test_script:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle
