version: 1.0.{build}-{branch}

environment:
  matrix:
    - NOV: 5
    - NOV: 4
    - NOV: 3
    - NOV: 2
    - NOV: 1
    - NOV: 0

platform:
  - x64
  - x86

cache:
  - node_modules

install:
  - ps: Install-Product node $env:NOV $env:PLATFORM
  - node -v
  - npm -v
  - npm install

build: off

test_script:
  - npm test
